import React, { useEffect, useMemo, useState } from 'react';
import {
  X,
  Trash2,
  Eraser,
  RotateCcw,
  Wrench,
  ChevronRight,
  Loader2,
  CheckCircle2,
  Database as DatabaseIcon,
} from 'lucide-react';
import { CopyableErrorBanner } from '../common/CopyableErrorBanner';
import { DatabaseConnection, SchemaColumnNode, SchemaTableNode, SchemaGroupNode } from '../../core/domain/types';
import { safeInvoke } from '../../core/tauri/ipc';
import { parseDbError } from '../../core/sql/dbError';
import { useEscapeToClose } from '../../core/hooks/useEscapeToClose';
import { useToastStore } from '../../store/useToastStore';
import { useTabStore } from '../../store/useTabStore';
import {
  getTableCapabilities,
  truncateTableSql,
  dropTableSql,
  resetAutoIncrementSql,
  analyzeTableSql,
  vacuumTableSql,
  optimizeTableSql,
  checkTableSql,
  reindexTableSql,
  maintenanceOpSql,
  maintenanceOpLabel,
  detectAutoIncrementColumn,
  MaintenanceOp,
  AutoIncrementMeta,
} from '../../core/sql/tableActions';
import { ConfirmDialog } from '../common/ConfirmDialog';
import { cn } from '../../core/utils/cn';

type ConfirmKind = 'drop' | 'truncate' | null;

export interface TableActionsContext {
  conn: DatabaseConnection;
  group: SchemaGroupNode;
  table: SchemaTableNode;
}

interface Props {
  ctx: TableActionsContext;
  /** Called after a successful schema-modifying op (DROP/TRUNCATE) so the tree refreshes. */
  onSchemaChanged: () => void;
  onClose: () => void;
  /** Optional initial focus — when 'reset', opens the reset-auto-increment section. */
  initialFocus?: 'reset' | null;
}

/**
 * The table actions modal: Truncate, Drop, Reset Auto Increment, and table
 * maintenance operations. All actions are capability-gated per engine and all
 * destructive actions route through `ConfirmDialog` with type-to-confirm.
 *
 * SQL is generated by the pure `tableActions.ts` helpers (never inline) and
 * executed via the existing `execute_query` command — the same path
 * `TableStructureModal.runDdl` uses.
 */
export const TableActionsDialog: React.FC<Props> = ({ ctx, onSchemaChanged, onClose, initialFocus }) => {
  useEscapeToClose(onClose);
  const { conn, group, table } = ctx;
  const engine = conn.engine;
  const schema = group.name;
  const caps = getTableCapabilities(engine);

  const [confirm, setConfirm] = useState<ConfirmKind>(null);
  const [running, setRunning] = useState(false);
  const [resultMsg, setResultMsg] = useState<{ ok: boolean; text: string } | null>(null);
  const [expandedSection, setExpandedSection] = useState<string | null>(
    initialFocus === 'reset' ? 'reset' : null
  );

  // Auto-increment state.
  const [autoInc, setAutoInc] = useState<AutoIncrementMeta | null | undefined>(undefined); // undefined = loading
  const [nextValue, setNextValue] = useState<string>('1');
  const [autoIncError, setAutoIncError] = useState<string | null>(null);

  const detectedAiColumn = useMemo(
    () => detectAutoIncrementColumn(engine, table.children),
    [engine, table.children]
  );

  // Load auto-increment metadata when the reset section is expanded.
  useEffect(() => {
    if (expandedSection !== 'reset') return;
    if (autoInc !== undefined) return; // already loaded
    if (!detectedAiColumn || !caps.supportsResetAutoIncrement) return;
    loadAutoInc();
  }, [expandedSection]); // eslint-disable-line react-hooks/exhaustive-deps

  const loadAutoInc = async () => {
    setAutoInc(undefined);
    setAutoIncError(null);
    try {
      const meta = await safeInvoke<AutoIncrementMeta | null>('get_table_auto_increment', {
        config: conn,
        schema,
        table: table.name,
      });
      setAutoInc(meta);
      // Default the next value to currentMax + 1 (or 1 if empty).
      const base = meta?.currentMax != null ? meta.currentMax + 1 : 1;
      setNextValue(String(base));
    } catch (err: any) {
      setAutoInc(null);
      setAutoIncError(err?.message ?? String(err));
    }
  };

  // ── Execution helper (mirrors runDdl from TableStructureModal) ──
  const runSql = async (sql: string, label: string): Promise<boolean> => {
    setRunning(true);
    setResultMsg(null);
    try {
      await safeInvoke('execute_query', {
        request: { config: conn, sql },
        queryId: `${label.replace(/\s+/g, '_')}_${table.name}_${Date.now()}`,
        __meta: { source: 'ddl' },
      });
      return true;
    } catch (err: any) {
      const parsed = parseDbError(err?.message ?? String(err));
      const msg = parsed.detail ? `${parsed.message} — ${parsed.detail}` : parsed.message;
      setResultMsg({ ok: false, text: msg });
      return false;
    } finally {
      setRunning(false);
    }
  };

  // ── Action handlers ──
  const handleDrop = async () => {
    const sql = dropTableSql(engine, table.name, schema);
    const ok = await runSql(sql, 'Drop Table');
    if (ok) {
      // Close any open tab for this table.
      useTabStore.getState().tabs
        .filter((t) => t.tableName === table.name && t.connectionId === conn.id)
        .forEach((t) => useTabStore.getState().closeTab(t.id));
      onSchemaChanged();
      useToastStore.getState().push({
        severity: 'success',
        title: 'Table dropped',
        message: `${table.name} was permanently deleted.`,
      });
      onClose();
    }
    setConfirm(null);
  };

  const handleTruncate = async () => {
    const sql = truncateTableSql(engine, table.name, schema);
    if (!sql) return;
    const ok = await runSql(sql, 'Truncate Table');
    if (ok) {
      onSchemaChanged();
      useToastStore.getState().push({
        severity: 'success',
        title: 'Table truncated',
        message: `All rows removed from ${table.name}.`,
      });
      setResultMsg({ ok: true, text: `All rows removed from ${table.name}. Structure, columns, and indexes are preserved.` });
    }
    setConfirm(null);
  };

  const handleResetAutoInc = async () => {
    const val = parseInt(nextValue, 10);
    if (Number.isNaN(val) || val < 1) {
      setResultMsg({ ok: false, text: 'Next ID must be a positive integer.' });
      return;
    }
    const sql = resetAutoIncrementSql(engine, table.name, val, autoInc ?? undefined);
    if (!sql) {
      setResultMsg({ ok: false, text: 'Resetting the auto-increment is not supported for this table.' });
      return;
    }
    const ok = await runSql(sql, 'Reset Auto Increment');
    if (ok) {
      useToastStore.getState().push({
        severity: 'success',
        title: 'Auto-increment reset',
        message: `Next value for ${table.name} set to ${val}.`,
      });
      setResultMsg({ ok: true, text: `Next auto-increment value set to ${val}.` });
      // Reload metadata to reflect the new value.
      loadAutoInc();
    }
  };

  const handleMaintenance = async (op: MaintenanceOp) => {
    let sql: string | null = null;
    switch (op) {
      case 'analyze': sql = analyzeTableSql(engine, table.name, schema); break;
      case 'vacuum': sql = vacuumTableSql(engine, table.name, schema); break;
      case 'optimize': sql = optimizeTableSql(engine, table.name, schema); break;
      case 'check': sql = checkTableSql(engine, table.name, schema); break;
      case 'reindex': sql = reindexTableSql(engine, table.name, schema); break;
      case 'checkpoint': sql = maintenanceOpSql('checkpoint', engine, table.name, schema); break;
    }
    if (!sql) return;
    const ok = await runSql(sql, maintenanceOpLabel(op));
    if (ok) {
      useToastStore.getState().push({
        severity: 'success',
        title: `${maintenanceOpLabel(op)} completed`,
        message: `${maintenanceOpLabel(op)} finished on ${table.name}.`,
      });
      setResultMsg({ ok: true, text: `${maintenanceOpLabel(op)} completed successfully on ${table.name}.` });
    }
  };

  const truncateSqlPreview = truncateTableSql(engine, table.name, schema);
  const dropSqlPreview = dropTableSql(engine, table.name, schema);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm" onClick={onClose}>
      <div
        className="w-full max-w-xl max-h-[85vh] bg-[#0a0f18] border border-[#1e293b] rounded-2xl shadow-2xl flex flex-col overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3 border-b border-[#1e293b]">
          <div className="flex items-center gap-2">
            <Wrench className="w-4 h-4 text-amber-400" />
            <span className="text-sm font-bold text-slate-100">Table Actions</span>
            <span className="text-xs text-slate-500 font-mono ml-1">{table.name}</span>
          </div>
          <button onClick={onClose} className="text-slate-500 hover:text-slate-300">
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-5 space-y-4">
          {/* Result banner */}
          {resultMsg && (
            resultMsg.ok ? (
              <div className="flex items-start gap-2 rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-2.5 text-[11px] text-emerald-300">
                <CheckCircle2 className="w-3.5 h-3.5 mt-0.5 shrink-0" />
                <span className="break-words">{resultMsg.text}</span>
              </div>
            ) : (
              <CopyableErrorBanner message={resultMsg.text} tone="rose" compact parseAsDbError />
            )
          )}

          {/* Reset Auto Increment */}
          <Section
            id="reset"
            title="Reset Auto Increment / Sequence"
            icon={RotateCcw}
            iconColor="text-blue-400"
            expanded={expandedSection === 'reset'}
            onToggle={() => setExpandedSection((s) => (s === 'reset' ? null : 'reset'))}
            disabledReason={
              !caps.supportsResetAutoIncrement
                ? 'Not supported for this database engine.'
                : !detectedAiColumn
                ? 'This table has no auto-increment / identity / sequence column.'
                : undefined
            }
          >
            {autoInc === undefined && detectedAiColumn ? (
              <div className="flex items-center gap-2 text-[11px] text-slate-500 py-2">
                <Loader2 className="w-3 h-3 animate-spin" /> Loading auto-increment metadata…
              </div>
            ) : autoIncError ? (
              <CopyableErrorBanner message={autoIncError} tone="rose" compact parseAsDbError />
            ) : !detectedAiColumn ? (
              <div className="text-[11px] text-slate-500 py-1">
                No auto-increment / identity / sequence-backed column was detected on this table.
              </div>
            ) : (
              <div className="space-y-3">
                <div className="grid grid-cols-2 gap-3 text-xs">
                  <Meta label="Column" value={autoInc?.columnName ?? detectedAiColumn} />
                  <Meta label="Current max ID" value={autoInc?.currentMax != null ? String(autoInc.currentMax) : '— (empty)'} />
                  {autoInc?.currentValue != null && (
                    <Meta label="Next value (current)" value={String(autoInc.currentValue)} />
                  )}
                  {autoInc?.sequenceName && (
                    <Meta label="Sequence" value={autoInc.sequenceName} mono />
                  )}
                </div>
                <div className="space-y-1.5">
                  <label className="block text-[11px] text-slate-500 font-semibold">Next ID</label>
                  <div className="flex items-center gap-2">
                    <input
                      type="number"
                      min={1}
                      value={nextValue}
                      onChange={(e) => setNextValue(e.target.value)}
                      className="w-32 bg-[#06090e] border border-[#1e293b] rounded-lg text-sm text-slate-200 px-3 py-1.5 font-mono focus:outline-none focus:border-cyan-500/50"
                    />
                    <button
                      onClick={handleResetAutoInc}
                      disabled={running}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white text-xs font-semibold"
                    >
                      {running ? <Loader2 className="w-3 h-3 animate-spin" /> : <RotateCcw className="w-3 h-3" />}
                      Reset
                    </button>
                  </div>
                  <p className="text-[10px] text-slate-600">
                    The next INSERT will receive this value. Existing rows are not modified.
                  </p>
                </div>
              </div>
            )}
          </Section>

          {/* Maintenance */}
          {caps.maintenanceOps.length > 0 && (
            <Section
              id="maintenance"
              title="Table Maintenance"
              icon={DatabaseIcon}
              iconColor="text-cyan-400"
              expanded={expandedSection === 'maintenance'}
              onToggle={() => setExpandedSection((s) => (s === 'maintenance' ? null : 'maintenance'))}
            >
              <div className="grid grid-cols-2 gap-2">
                {caps.maintenanceOps.map((op) => (
                  <button
                    key={op}
                    onClick={() => handleMaintenance(op)}
                    disabled={running}
                    className="flex items-center gap-2 px-3 py-2 rounded-lg bg-[#141e33] hover:bg-[#1e293b] disabled:opacity-50 text-xs text-slate-200 border border-[#1e293b] transition-colors"
                  >
                    <DatabaseIcon className="w-3 h-3 text-cyan-400" />
                    {maintenanceOpLabel(op)}
                  </button>
                ))}
              </div>
              <p className="text-[10px] text-slate-600 mt-2">
                These operations refresh statistics, reclaim space, or verify integrity. They are safe and non-destructive.
              </p>
            </Section>
          )}

          <div className="h-px bg-[#1e293b]" />

          {/* Destructive actions */}
          <div className="space-y-2">
            {/* Truncate */}
            <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 px-4 py-3 flex items-center gap-3">
              <Eraser className="w-4 h-4 text-amber-400 shrink-0" />
              <div className="flex-1 min-w-0">
                <div className="text-xs font-semibold text-amber-300">Truncate Table</div>
                <div className="text-[11px] text-slate-500">
                  {caps.supportsTruncate
                    ? 'Remove all rows. Structure, columns, and indexes are preserved.'
                    : 'Remove all rows via DELETE (this engine has no TRUNCATE). Structure is preserved.'}
                </div>
              </div>
              <button
                onClick={() => { setResultMsg(null); setConfirm('truncate'); }}
                disabled={running || !truncateSqlPreview}
                className="px-3 py-1.5 rounded-lg bg-amber-600/90 hover:bg-amber-500 disabled:opacity-50 text-white text-xs font-semibold shrink-0"
              >
                Truncate
              </button>
            </div>

            {/* Drop — most destructive, visually separated */}
            <div className="rounded-xl border border-rose-500/30 bg-rose-500/5 px-4 py-3 flex items-center gap-3">
              <Trash2 className="w-4 h-4 text-rose-400 shrink-0" />
              <div className="flex-1 min-w-0">
                <div className="text-xs font-semibold text-rose-300">Drop Table</div>
                <div className="text-[11px] text-slate-500">
                  Permanently delete the table, including all rows, columns, indexes, and constraints. This cannot be undone.
                </div>
              </div>
              <button
                onClick={() => { setResultMsg(null); setConfirm('drop'); }}
                disabled={running}
                className="px-3 py-1.5 rounded-lg bg-rose-600 hover:bg-rose-500 disabled:opacity-50 text-white text-xs font-semibold shrink-0"
              >
                Drop Table
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Confirmation dialogs */}
      {confirm === 'drop' && (
        <ConfirmDialog
          title="Drop Table"
          tone="danger"
          confirmLabel="Drop Table"
          requireText={table.name}
          requireTextLabel={`Type the table name to confirm:`}
          message={
            <div className="space-y-2">
              <p>
                You are about to permanently delete <span className="font-mono text-rose-300">{table.name}</span>, including:
              </p>
              <ul className="list-disc list-inside text-slate-500 space-y-0.5 ml-2">
                <li>all rows</li>
                <li>columns and data types</li>
                <li>indexes</li>
                <li>constraints</li>
                <li>table definition</li>
              </ul>
              <p className="text-rose-300 font-semibold">This action cannot be undone.</p>
              <SqlPreview sql={dropSqlPreview} />
            </div>
          }
          onConfirm={handleDrop}
          onClose={() => setConfirm(null)}
          loading={running}
        />
      )}

      {confirm === 'truncate' && (
        <ConfirmDialog
          title="Truncate Table"
          tone="warning"
          confirmLabel="Truncate Table"
          requireText={table.name}
          requireTextLabel={`Type the table name to confirm:`}
          message={
            <div className="space-y-2">
              <p>
                You are about to remove <span className="font-semibold text-amber-300">all rows</span> from{' '}
                <span className="font-mono text-amber-300">{table.name}</span>.
              </p>
              <p className="text-slate-500">
                The table structure, columns, and indexes will be preserved. This cannot be undone.
              </p>
              {truncateSqlPreview && <SqlPreview sql={truncateSqlPreview} />}
            </div>
          }
          onConfirm={handleTruncate}
          onClose={() => setConfirm(null)}
          loading={running}
        />
      )}
    </div>
  );
};

// ── Small presentational helpers ──

const Section: React.FC<{
  id: string;
  title: string;
  icon: React.ComponentType<{ className?: string }>;
  iconColor: string;
  expanded: boolean;
  onToggle: () => void;
  disabledReason?: string;
  children: React.ReactNode;
}> = ({ title, icon: Icon, iconColor, expanded, onToggle, disabledReason, children }) => {
  const disabled = !!disabledReason;
  return (
    <div className={cn('rounded-xl border border-[#1e293b] overflow-hidden', disabled && 'opacity-60')}>
      <button
        onClick={onToggle}
        disabled={disabled}
        title={disabledReason}
        className="w-full flex items-center gap-2 px-4 py-2.5 hover:bg-[#0d1117] disabled:cursor-not-allowed text-left"
      >
        <Icon className={cn('w-3.5 h-3.5', iconColor)} />
        <span className="text-xs font-semibold text-slate-200 flex-1">{title}</span>
        {disabledReason ? (
          <span className="text-[9px] text-slate-600 uppercase">{disabledReason}</span>
        ) : (
          <ChevronRight className={cn('w-3.5 h-3.5 text-slate-500 transition-transform', expanded && 'rotate-90')} />
        )}
      </button>
      {expanded && !disabled && <div className="px-4 pb-3">{children}</div>}
    </div>
  );
};

const Meta: React.FC<{ label: string; value: string; mono?: boolean }> = ({ label, value, mono }) => (
  <div>
    <div className="text-[10px] uppercase tracking-wider text-slate-600 font-semibold">{label}</div>
    <div className={cn('text-slate-300 text-xs mt-0.5 truncate', mono && 'font-mono')} title={value}>
      {value}
    </div>
  </div>
);

const SqlPreview: React.FC<{ sql: string }> = ({ sql }) => (
  <div>
    <div className="text-[10px] uppercase tracking-wider text-slate-600 font-semibold mb-1">SQL</div>
    <pre className="bg-[#06090e] border border-[#1e293b] rounded-lg p-2.5 text-[11px] font-mono text-slate-400 overflow-x-auto whitespace-pre-wrap break-all">
      {sql}
    </pre>
  </div>
);
